# Generated by Django 6.0.2 on 2026-02-19 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='Fayl nomi')),
                ('stored_file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Fayl')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Hajm (bayt)')),
                ('sha256', models.CharField(blank=True, default='', max_length=64, verbose_name='SHA-256')),
                ('mime_type', models.CharField(blank=True, default='', max_length=120, verbose_name='MIME')),
                ('detected_type', models.CharField(blank=True, default='', max_length=16, verbose_name='Turi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Namuna',
                'verbose_name_plural': 'Namunalar',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.IntegerField(default=0, verbose_name='Ball (%)')),
                ('verdict', models.CharField(choices=[('benign', 'Toza'), ('suspicious', 'Shubhali'), ('malicious', 'Zararli'), ('unknown', 'Noma’lum')], default='unknown', max_length=16, verbose_name='Xulosa')),
                ('model_used', models.CharField(blank=True, default='', max_length=32, verbose_name='Model')),
                ('model_version', models.CharField(blank=True, default='v1', max_length=32, verbose_name='Versiya')),
                ('reasons_json', models.JSONField(blank=True, default=dict, verbose_name='Sabablar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tekshiruv vaqti')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scanner.sample', verbose_name='Namuna')),
            ],
            options={
                'verbose_name': 'Tekshiruv',
                'verbose_name_plural': 'Tekshiruvlar',
            },
        ),
    ]
